version: '3.7'
services:

  # docker pull postgres:16.0-alpine3.18
  # Environment
  bank-db:
    image: postgres:16.0-alpine
    hostname: bank-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

